import { SpotifyApi } from '@spotify/web-api-ts-sdk';
import { RemixContainer } from '../data/TrackContainer';
import { TrackList } from '../components/TrackList';
import { RemixOptions } from '../data/RemixFunctions';
import { useState, useEffect } from 'react';
import { ExportController, ProgressHandler } from '../data/ExportController';
import { JSONExportTarget, PlaylistExportTarget, GitHubPagesExportTarget } from '../data/Exporters';
import { ExportProgressOverlay } from '../components/ExportProgressOverlay';

interface ExportPageProps {
  sdk: SpotifyApi;
  remixContainer: RemixContainer<RemixOptions> | null;
  excludedTrackIds: Set<string>;
  setExcludedTrackIds: React.Dispatch<React.SetStateAction<Set<string>>>;
}

export function ExportPage({ sdk, remixContainer, excludedTrackIds, setExcludedTrackIds }: ExportPageProps) {
  const [refreshCounter] = useState(0);
  const [exportType, setExportType] = useState<'playlist' | 'json' | 'github'>('playlist');
  const [playlistName, setPlaylistName] = useState('Spotter Remix');
  const [playlistDescription, setPlaylistDescription] = useState('Generated by Spotter');
  const [siteName, setSiteName] = useState('My Music Collection');
  const [siteDescription, setSiteDescription] = useState('Generated by Spotter');
  const [isExporting, setIsExporting] = useState(false);
  const [filteredTrackCount, setFilteredTrackCount] = useState<number | null>(null);
  const [lastCreatedPlaylistId, setLastCreatedPlaylistId] = useState<string | null>(null);
  
  // Progress tracking state
  const [progressDescription, setProgressDescription] = useState('');
  const [progressCompleted, setProgressCompleted] = useState(0);
  const [progressTracksProcessed, setProgressTracksProcessed] = useState(0);
  const [progressTotalTracks, setProgressTotalTracks] = useState(0);
  
  // Completion state
  const [isCompleted, setIsCompleted] = useState(false);
  const [completionMessage, setCompletionMessage] = useState('');
  const [completionSpotifyId, setCompletionSpotifyId] = useState<string | null>(null);

  const updateFilteredTrackCount = async () => {
    if (!remixContainer) {
      setFilteredTrackCount(null);
      return;
    }
    
    try {
      const response = await remixContainer.getTracks(-1); // Get all tracks
      const count = response.items.filter(track => !excludedTrackIds.has(track.id)).length;
      setFilteredTrackCount(count);
    } catch (error) {
      console.error('Failed to count filtered tracks:', error);
      setFilteredTrackCount(null);
    }
  };

  // Update count when container or excluded tracks change
  useEffect(() => {
    updateFilteredTrackCount();
  }, [remixContainer, excludedTrackIds]);

  // Progress handler for export operations
  const createProgressHandler = (totalTracks: number): ProgressHandler => {
    return (description: string, completed: number, numberProcessed: number) => {
      setProgressDescription(description);
      setProgressCompleted(completed);
      setProgressTracksProcessed(numberProcessed);
      setProgressTotalTracks(totalTracks);
    };
  };

  // Handle dismissing the completion overlay
  const handleDismissCompletion = () => {
    setIsCompleted(false);
    setIsExporting(false);
    setCompletionMessage('');
    setCompletionSpotifyId(null);
    // Reset progress state
    setProgressDescription('');
    setProgressCompleted(0);
    setProgressTracksProcessed(0);
    setProgressTotalTracks(0);
  };

  // Simple function to create ZIP-like structure (for now just create individual files)
  const createZipFile = async (files: { [key: string]: string }): Promise<Blob> => {
    // For simplicity, we'll create a JSON file containing all the files
    // In a real implementation, you'd use a library like JSZip
    const zipContent = {
      message: "Extract these files to create your GitHub Pages site:",
      instructions: [
        "1. Create a new repository on GitHub",
        "2. Enable GitHub Pages in repository settings", 
        "3. Upload these files to the repository",
        "4. Your site will be available at username.github.io/repository-name"
      ],
      files: files
    };
    
    return new Blob([JSON.stringify(zipContent, null, 2)], { type: 'application/json' });
  };

  const getFilteredTracks = async () => {
    if (!remixContainer) return [];
    
    const response = await remixContainer.getTracks(-1); // Get all tracks
    // Filter out excluded tracks
    return response.items.filter(track => !excludedTrackIds.has(track.id));
  };

  const handleExport = async () => {
    if (!remixContainer) return;
    
    setIsExporting(true);
    try {
      const filteredTracks = await getFilteredTracks();
      
      // Create progress handler
      const progressHandler = createProgressHandler(filteredTracks.length);
      
      if (exportType === 'json') {
        // Use ExportController with JSONExportTarget
        const jsonTarget = new JSONExportTarget();
        const controller = new ExportController(jsonTarget, 3, progressHandler); // 3 retries for JSON export
        
        await controller.append(filteredTracks);
        const jsonData = await jsonTarget.getData();
        
        // Download the JSON file
        const blob = new Blob([jsonData], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${playlistName.replace(/[^a-zA-Z0-9]/g, '_')}.json`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        
        // Show completion
        setCompletionMessage(`Successfully exported ${filteredTracks.length} tracks to JSON file`);
        setIsCompleted(true);
      } else if (exportType === 'github') {
        // Use ExportController with GitHubPagesExportTarget
        const githubTarget = new GitHubPagesExportTarget({ siteName, siteDescription });
        const controller = new ExportController(githubTarget, 3, progressHandler); // 3 retries for GitHub export
        
        await controller.append(filteredTracks);
        const siteData = await githubTarget.getData();
        
        // Create ZIP file with all the site files
        const zip = await createZipFile(siteData.files);
        const blob = new Blob([zip], { type: 'application/zip' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${siteName.replace(/[^a-zA-Z0-9]/g, '_')}_github_pages.zip`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        
        // Show completion
        setCompletionMessage(`Successfully created GitHub Pages site with ${filteredTracks.length} tracks`);
        setIsCompleted(true);
      } else {
        // Use ExportController with PlaylistExportTarget
        const playlistTarget = new PlaylistExportTarget(sdk, { name: playlistName, description: playlistDescription });
        const controller = new ExportController(playlistTarget, 5, progressHandler); // 5 retries for Spotify API (may be more flaky)
        
        await controller.append(filteredTracks); // Let target determine optimal batch size
        const playlistId = playlistTarget.getPlaylistId();
        setLastCreatedPlaylistId(playlistId);
        
        // Show completion with Spotify link
        setCompletionMessage(`Created playlist "${playlistName}" with ${filteredTracks.length} tracks`);
        setCompletionSpotifyId(playlistId);
        setIsCompleted(true);
      }
    } catch (error) {
      console.error('Export failed:', error);
      
      // Provide more specific error messages
      let errorMessage = 'Export failed. Please try again.';
      if (error instanceof Error) {
        if (error.message.includes('playlist')) {
          errorMessage = 'Failed to create playlist. Please check your Spotify permissions and try again.';
        } else if (error.message.includes('track')) {
          errorMessage = 'Failed to add tracks to playlist. Some tracks may not be available.';
        } else if (error.message.includes('network') || error.message.includes('fetch')) {
          errorMessage = 'Network error. Please check your internet connection and try again.';
        }
      }
      
      alert(errorMessage);
      setIsExporting(false);
      // Reset progress state on error
      setProgressDescription('');
      setProgressCompleted(0);
      setProgressTracksProcessed(0);
      setProgressTotalTracks(0);
    }
    // Note: We don't reset state in finally block anymore since completion state handles it
  };

  const getActionButtonLabel = () => {
    if (isExporting) return 'Exporting...';
    if (exportType === 'json') return 'Download JSON';
    if (exportType === 'github') return 'Download GitHub Pages';
    return 'Create Playlist';
  };

  return (
    <div className="select-items-container export-page">
      {/* Progress Overlay */}
      <ExportProgressOverlay
        description={progressDescription}
        completed={progressCompleted}
        tracksProcessed={progressTracksProcessed}
        totalTracks={progressTotalTracks}
        isVisible={isExporting || isCompleted}
        isCompleted={isCompleted}
        completionMessage={completionMessage}
        spotifyPlaylistId={completionSpotifyId || undefined}
        onDismiss={handleDismissCompletion}
      />
      
      <div className="content-area">
        <div className="left-panel">
          {/* Track List showing the remix */}
          <div className="track-list-area">
            {remixContainer ? (
              <div className="playlist-container">
                <TrackList 
                  trackContainer={remixContainer} 
                  refreshTrigger={refreshCounter}
                  excludedTrackIds={excludedTrackIds}
                  setExcludedTrackIds={setExcludedTrackIds}
                />
              </div>
            ) : (
              <div className="playlist-container">
                <div className="no-results">
                  No remix available. Go to Remix page to create one.
                </div>
              </div>
            )}
          </div>
        </div>

        <div className="right-panel">
          {/* Export Controls */}
          <div className="export-controls">
            <h3>Export Options</h3>
            
            {remixContainer ? (
              <div className="export-options">
                <div className="export-info">
                  <p className="track-count">
                    {filteredTrackCount !== null 
                      ? `${filteredTrackCount} tracks selected for export`
                      : 'Loading track count...'}
                  </p>
                </div>
                
                <div className="export-group">
                  <label className="control-label">Format</label>
                  <select 
                    className="control-select"
                    value={exportType}
                    onChange={(e) => setExportType(e.target.value as 'playlist' | 'json' | 'github')}
                  >
                    <option value="playlist">Spotify Playlist</option>
                    <option value="json">JSON Export</option>
                    <option value="github">GitHub Pages Site</option>
                  </select>
                </div>
                
                {exportType === 'playlist' && (
                  <>
                    <div className="export-group">
                      <label className="control-label">Playlist Name</label>
                      <input 
                        type="text" 
                        className="control-input"
                        value={playlistName}
                        onChange={(e) => {
                          setPlaylistName(e.target.value);
                          setLastCreatedPlaylistId(null); // Clear old playlist link
                        }}
                        placeholder="Enter playlist name"
                      />
                    </div>
                    
                    <div className="export-group">
                      <label className="control-label">Description</label>
                      <textarea 
                        className="control-textarea"
                        value={playlistDescription}
                        onChange={(e) => setPlaylistDescription(e.target.value)}
                        placeholder="Enter playlist description"
                        rows={3}
                      />
                    </div>
                  </>
                )}
                
                {exportType === 'github' && (
                  <>
                    <div className="export-group">
                      <label className="control-label">Site Name</label>
                      <input 
                        type="text" 
                        className="control-input"
                        value={siteName}
                        onChange={(e) => setSiteName(e.target.value)}
                        placeholder="Enter site name"
                      />
                    </div>
                    
                    <div className="export-group">
                      <label className="control-label">Site Description</label>
                      <textarea 
                        className="control-textarea"
                        value={siteDescription}
                        onChange={(e) => setSiteDescription(e.target.value)}
                        placeholder="Enter site description"
                        rows={3}
                      />
                    </div>
                    
                    <div className="export-group">
                      <label className="control-label">About GitHub Pages</label>
                      <div className="export-info-text">
                        Creates a static website that you can host on GitHub Pages. 
                        The site will include a searchable track list with filtering options.
                      </div>
                    </div>
                  </>
                )}
                
                {lastCreatedPlaylistId && exportType === 'playlist' && (
                  <div className="export-group">
                    <label className="control-label">Last Created Playlist</label>
                    <div className="playlist-link-container">
                      <button 
                        type="button"
                        className="playlist-link-button"
                        onClick={() => window.open(`https://open.spotify.com/playlist/${lastCreatedPlaylistId}`, '_blank')}
                      >
                        Open in Spotify
                      </button>
                    </div>
                  </div>
                )}
                
                <div className="export-actions">
                  <button 
                    className="export-button primary"
                    onClick={handleExport}
                    disabled={isExporting || filteredTrackCount === 0}
                  >
                    {getActionButtonLabel()}
                  </button>
                </div>
              </div>
            ) : (
              <div className="no-export">
                <p>Create a remix first to enable export options.</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}