import { SpotifyApi } from '@spotify/web-api-ts-sdk';
import { RemixContainer } from '../data/TrackContainer';
import { TrackList } from '../components/TrackList';
import { RemixOptions } from '../data/RemixFunctions';
import { useState, useEffect } from 'react';
import { ExportController } from '../data/ExportController';
import { JSONExportTarget } from '../data/Exporters';

interface ExportPageProps {
  sdk: SpotifyApi;
  remixContainer: RemixContainer<RemixOptions> | null;
  excludedTrackIds: Set<string>;
  setExcludedTrackIds: React.Dispatch<React.SetStateAction<Set<string>>>;
}

export function ExportPage({ sdk, remixContainer, excludedTrackIds, setExcludedTrackIds }: ExportPageProps) {
  const [refreshCounter] = useState(0);
  const [exportType, setExportType] = useState<'playlist' | 'json'>('playlist');
  const [playlistName, setPlaylistName] = useState('Spotter Remix');
  const [playlistDescription, setPlaylistDescription] = useState('Generated by Spotter');
  const [isExporting, setIsExporting] = useState(false);
  const [filteredTrackCount, setFilteredTrackCount] = useState<number | null>(null);

  const updateFilteredTrackCount = async () => {
    if (!remixContainer) {
      setFilteredTrackCount(null);
      return;
    }
    
    try {
      const response = await remixContainer.getTracks(-1); // Get all tracks
      const count = response.items.filter(track => !excludedTrackIds.has(track.id)).length;
      setFilteredTrackCount(count);
    } catch (error) {
      console.error('Failed to count filtered tracks:', error);
      setFilteredTrackCount(null);
    }
  };

  // Update count when container or excluded tracks change
  useEffect(() => {
    updateFilteredTrackCount();
  }, [remixContainer, excludedTrackIds]);

  const getFilteredTracks = async () => {
    if (!remixContainer) return [];
    
    const response = await remixContainer.getTracks(-1); // Get all tracks
    // Filter out excluded tracks
    return response.items.filter(track => !excludedTrackIds.has(track.id));
  };

  const handleExport = async () => {
    if (!remixContainer) return;
    
    setIsExporting(true);
    try {
      const filteredTracks = await getFilteredTracks();
      
      if (exportType === 'json') {
        // Use ExportController with JSONExportTarget
        const jsonTarget = new JSONExportTarget();
        const controller = new ExportController(jsonTarget);
        
        await controller.append(filteredTracks);
        const jsonData = await jsonTarget.getData();
        
        // Download the JSON file
        const blob = new Blob([jsonData], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${playlistName.replace(/[^a-zA-Z0-9]/g, '_')}.json`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
      } else {
        // Create Spotify playlist
        const user = await sdk.currentUser.profile();
        const playlist = await sdk.playlists.createPlaylist(
          user.id,
          {
            name: playlistName,
            description: playlistDescription,
            public: false
          }
        );
        
        // Add tracks to playlist in batches
        const trackUris = filteredTracks.map(track => track.uri);
        const batchSize = 100; // Spotify API limit
        
        for (let i = 0; i < trackUris.length; i += batchSize) {
          const batch = trackUris.slice(i, i + batchSize);
          await sdk.playlists.addItemsToPlaylist(playlist.id, batch);
        }
        
        alert(`Created playlist "${playlistName}" with ${filteredTracks.length} tracks`);
      }
    } catch (error) {
      console.error('Export failed:', error);
      alert('Export failed. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  const getActionButtonLabel = () => {
    if (isExporting) return 'Exporting...';
    if (exportType === 'json') return 'Download JSON';
    return 'Create Playlist';
  };

  return (
    <div className="select-items-container export-page">
      <div className="content-area">
        <div className="left-panel">
          {/* Track List showing the remix */}
          <div className="track-list-area">
            {remixContainer ? (
              <div className="playlist-container">
                <TrackList 
                  trackContainer={remixContainer} 
                  refreshTrigger={refreshCounter}
                  excludedTrackIds={excludedTrackIds}
                  setExcludedTrackIds={setExcludedTrackIds}
                />
              </div>
            ) : (
              <div className="playlist-container">
                <div className="no-results">
                  No remix available. Go to Remix page to create one.
                </div>
              </div>
            )}
          </div>
        </div>

        <div className="right-panel">
          {/* Export Controls */}
          <div className="export-controls">
            <h3>Export Options</h3>
            
            {remixContainer ? (
              <div className="export-options">
                <div className="export-info">
                  <p className="track-count">
                    {filteredTrackCount !== null 
                      ? `${filteredTrackCount} tracks selected for export`
                      : 'Loading track count...'}
                  </p>
                </div>
                
                <div className="export-group">
                  <label className="control-label">Format</label>
                  <select 
                    className="control-select"
                    value={exportType}
                    onChange={(e) => setExportType(e.target.value as 'playlist' | 'json')}
                  >
                    <option value="playlist">Spotify Playlist</option>
                    <option value="json">JSON Export</option>
                  </select>
                </div>
                
                {exportType === 'playlist' && (
                  <>
                    <div className="export-group">
                      <label className="control-label">Playlist Name</label>
                      <input 
                        type="text" 
                        className="control-input"
                        value={playlistName}
                        onChange={(e) => setPlaylistName(e.target.value)}
                        placeholder="Enter playlist name"
                      />
                    </div>
                    
                    <div className="export-group">
                      <label className="control-label">Description</label>
                      <textarea 
                        className="control-textarea"
                        value={playlistDescription}
                        onChange={(e) => setPlaylistDescription(e.target.value)}
                        placeholder="Enter playlist description"
                        rows={3}
                      />
                    </div>
                  </>
                )}
                
                <div className="export-actions">
                  <button 
                    className="export-button primary"
                    onClick={handleExport}
                    disabled={isExporting || filteredTrackCount === 0}
                  >
                    {getActionButtonLabel()}
                  </button>
                </div>
              </div>
            ) : (
              <div className="no-export">
                <p>Create a remix first to enable export options.</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}