import { ChangeEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { SpotifyApi } from '@spotify/web-api-ts-sdk';
import { RemixContainer } from '../data/TrackContainer';
import { RemixOptions } from '../data/RemixFunctions';
import { ExportController, ProgressHandler } from '../data/ExportController';
import { JSONExportTarget, PlaylistExportTarget } from '../data/Exporters';
import { ExportProgressOverlay } from './ExportProgressOverlay';
import './ExportPane.css';

export type ExportPaneExportType = 'playlist' | 'json';

interface ExportPaneProps {
  sdk: SpotifyApi;
  remixContainer: RemixContainer<RemixOptions> | null;
  excludedTrackIds: Set<string>;
  initialExportType?: ExportPaneExportType;
  initialPlaylistName?: string;
  initialPlaylistDescription?: string;
  className?: string;
}

export function ExportPane({
  sdk,
  remixContainer,
  excludedTrackIds,
  initialExportType = 'playlist',
  initialPlaylistName = 'Spotter Remix',
  initialPlaylistDescription = 'Generated by Spotter',
  className
}: ExportPaneProps) {
  const [exportType, setExportType] = useState<ExportPaneExportType>(initialExportType);
  const [playlistName, setPlaylistName] = useState(initialPlaylistName);
  const [playlistDescription, setPlaylistDescription] = useState(initialPlaylistDescription);
  const [isExporting, setIsExporting] = useState(false);
  const [filteredTrackCount, setFilteredTrackCount] = useState<number | null>(null);
  const [lastCreatedPlaylistId, setLastCreatedPlaylistId] = useState<string | null>(null);

  const [progressDescription, setProgressDescription] = useState('');
  const [progressCompleted, setProgressCompleted] = useState(0);
  const [progressTracksProcessed, setProgressTracksProcessed] = useState(0);
  const [progressTotalTracks, setProgressTotalTracks] = useState(0);
  const [isCompleted, setIsCompleted] = useState(false);
  const [completionMessage, setCompletionMessage] = useState('');
  const [completionSpotifyId, setCompletionSpotifyId] = useState<string | null>(null);

  const hasRemix = Boolean(remixContainer);

  useEffect(() => {
    let cancelled = false;
    const updateFilteredTrackCount = async () => {
      if (!remixContainer) {
        if (!cancelled) {
          setFilteredTrackCount(null);
        }
        return;
      }

      try {
        const response = await remixContainer.getTracks(-1);
        const count = response.items.filter(track => !excludedTrackIds.has(track.id)).length;
        if (!cancelled) {
          setFilteredTrackCount(count);
        }
      } catch (error) {
        console.error('ExportPane: failed to count filtered tracks', error);
        if (!cancelled) {
          setFilteredTrackCount(null);
        }
      }
    };

    updateFilteredTrackCount();
    return () => {
      cancelled = true;
    };
  }, [remixContainer, excludedTrackIds]);

  const handleExportTypeChange = (event: ChangeEvent<HTMLSelectElement>) => {
    setExportType(event.target.value as ExportPaneExportType);
  };

  const handlePlaylistNameChange = (event: ChangeEvent<HTMLInputElement>) => {
    setPlaylistName(event.target.value);
    setLastCreatedPlaylistId(null);
  };

  const handlePlaylistDescriptionChange = (event: ChangeEvent<HTMLTextAreaElement>) => {
    setPlaylistDescription(event.target.value);
  };

  const handleDismissCompletion = () => {
    setIsCompleted(false);
    setIsExporting(false);
    setCompletionMessage('');
    setCompletionSpotifyId(null);
    setProgressDescription('');
    setProgressCompleted(0);
    setProgressTracksProcessed(0);
    setProgressTotalTracks(0);
  };

  const handleOpenPlaylist = () => {
    if (!lastCreatedPlaylistId) {
      return;
    }
    window.open(`https://open.spotify.com/playlist/${lastCreatedPlaylistId}`, '_blank');
  };

  const getFilteredTracks = useCallback(async () => {
    if (!remixContainer) {
      return [];
    }
    const response = await remixContainer.getTracks(-1);
    return response.items.filter(track => !excludedTrackIds.has(track.id));
  }, [remixContainer, excludedTrackIds]);

  const createProgressHandler = useCallback(
    (totalTracks: number): ProgressHandler => {
      return (description: string, completed: number, numberProcessed: number) => {
        setProgressDescription(description);
        setProgressCompleted(completed);
        setProgressTracksProcessed(numberProcessed);
        setProgressTotalTracks(totalTracks);
      };
    },
    []
  );

  const handleExport = useCallback(async () => {
    if (!remixContainer) {
      return;
    }

    setIsExporting(true);
    try {
      const filteredTracks = await getFilteredTracks();
      const progressHandler = createProgressHandler(filteredTracks.length);

      if (exportType === 'json') {
        const jsonTarget = new JSONExportTarget();
        const controller = new ExportController(jsonTarget, 3, progressHandler);

        await controller.append(filteredTracks);
        const jsonData = await jsonTarget.getData();

        const blob = new Blob([jsonData], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const anchor = document.createElement('a');
        anchor.href = url;
        anchor.download = `${playlistName.replace(/[^a-zA-Z0-9]/g, '_')}.json`;
        document.body.appendChild(anchor);
        anchor.click();
        document.body.removeChild(anchor);
        URL.revokeObjectURL(url);

        setCompletionMessage(`Successfully exported ${filteredTracks.length} tracks to JSON file`);
        setCompletionSpotifyId(null);
        setIsCompleted(true);
      } else {
        const playlistTarget = new PlaylistExportTarget(sdk, {
          name: playlistName,
          description: playlistDescription
        });
        const controller = new ExportController(playlistTarget, 5, progressHandler);

        await controller.append(filteredTracks);
        const playlistId = playlistTarget.getPlaylistId();
        setLastCreatedPlaylistId(playlistId);
        setCompletionMessage(
          `Created playlist "${playlistName}" with ${filteredTracks.length} tracks`
        );
        setCompletionSpotifyId(playlistId);
        setIsCompleted(true);
      }
    } catch (error) {
      console.error('ExportPane: export failed', error);
      let errorMessage = 'Export failed. Please try again.';
      if (error instanceof Error) {
        if (error.message.includes('playlist')) {
          errorMessage = 'Failed to create playlist. Please check your Spotify permissions and try again.';
        } else if (error.message.includes('track')) {
          errorMessage = 'Failed to add tracks to playlist. Some tracks may not be available.';
        } else if (error.message.includes('network') || error.message.includes('fetch')) {
          errorMessage = 'Network error. Please check your internet connection and try again.';
        }
      }
      alert(errorMessage);
      setIsExporting(false);
      setProgressDescription('');
      setProgressCompleted(0);
      setProgressTracksProcessed(0);
      setProgressTotalTracks(0);
    }
  }, [createProgressHandler, exportType, getFilteredTracks, playlistDescription, playlistName, remixContainer, sdk]);

  const actionButtonLabel = useMemo(() => {
    if (isExporting) {
      return 'Exporting...';
    }
    return exportType === 'json' ? 'Download JSON' : 'Create Playlist';
  }, [exportType, isExporting]);

  const disableExportButton = !hasRemix || filteredTrackCount === 0;

  const trackCountLabel = filteredTrackCount === null
    ? 'Export tracks to'
    : `Export ${filteredTrackCount} track${filteredTrackCount === 1 ? '' : 's'} to`;

  const containerClasses = ['export-pane-container'];
  if (className) {
    containerClasses.push(className);
  }

  if (!hasRemix) {
    return (
      <div className={containerClasses.join(' ')}>
        <ExportProgressOverlay
          description={progressDescription}
          completed={progressCompleted}
          tracksProcessed={progressTracksProcessed}
          totalTracks={progressTotalTracks}
          isVisible={isExporting || isCompleted}
          isCompleted={isCompleted}
          completionMessage={completionMessage}
          spotifyPlaylistId={completionSpotifyId ?? undefined}
          onDismiss={handleDismissCompletion}
        />
        <div className="export-pane">
          <div className="no-export">
            <p>Create a remix first to enable export options.</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className={containerClasses.join(' ')}>
      <ExportProgressOverlay
        description={progressDescription}
        completed={progressCompleted}
        tracksProcessed={progressTracksProcessed}
        totalTracks={progressTotalTracks}
        isVisible={isExporting || isCompleted}
        isCompleted={isCompleted}
        completionMessage={completionMessage}
        spotifyPlaylistId={completionSpotifyId ?? undefined}
        onDismiss={handleDismissCompletion}
      />
      <div className="export-pane">
        <div className="export-options">
          <div className="export-pane__format-row">
            <label className="export-pane__format-label" htmlFor="export-format">
              {trackCountLabel}
            </label>
            <select
              id="export-format"
              className="control-select"
              value={exportType}
              onChange={handleExportTypeChange}
            >
              <option value="playlist">Spotify Playlist</option>
              <option value="json">JSON Export</option>
            </select>
          </div>

          {exportType === 'playlist' && (
            <>
              <div className="export-group">
                <label className="control-label" htmlFor="playlist-name">
                  Playlist Name
                </label>
                <input
                  id="playlist-name"
                  type="text"
                  className="control-input"
                  value={playlistName}
                  onChange={handlePlaylistNameChange}
                  placeholder="Enter playlist name"
                />
              </div>

              <div className="export-group">
                <label className="control-label" htmlFor="playlist-description">
                  Description
                </label>
                <textarea
                  id="playlist-description"
                  className="control-textarea"
                  value={playlistDescription}
                  onChange={handlePlaylistDescriptionChange}
                  placeholder="Enter playlist description"
                  rows={3}
                />
              </div>
            </>
          )}

          {exportType === 'playlist' && lastCreatedPlaylistId && (
            <div className="export-group">
              <label className="control-label" htmlFor="last-created-playlist">
                Last Created Playlist
              </label>
              <div className="playlist-link-container">
                <button
                  id="last-created-playlist"
                  type="button"
                  className="playlist-link-button"
                  onClick={handleOpenPlaylist}
                >
                  Open in Spotify
                </button>
              </div>
            </div>
          )}

          <div className="export-actions">
            <button
              className="export-button primary"
              onClick={handleExport}
              disabled={isExporting || disableExportButton}
            >
              {actionButtonLabel}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
